events {}

http {
  server {
    listen 80;

    location /api/ {
      proxy_pass http://ms1:3000/;
      proxy_set_header Host $host;
    }

    location /agent/ {
      proxy_pass http://ms2:8000/;
      proxy_set_header Host $host;
    }
  }
}